name: raylab
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.3
  - appnope=0.1.0
  - asn1crypto=1.3.0
  - astroid=2.3.3
  - attrs=19.3.0
  - backcall=0.1.0
  - black=19.10b0
  - blas=1.0
  - bleach=3.1.4
  - bokeh=2.0.1
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - cfgv=3.1.0
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=2.8
  - decorator=4.4.2
  - defusedxml=0.6.0
  - editdistance=0.5.3
  - entrypoints=0.3
  - freetype=2.9.1
  - identify=1.4.14
  - idna=2.9
  - importlib-metadata=1.6.0
  - importlib_metadata=1.5.0
  - intel-openmp=2019.4
  - ipykernel=5.2.0
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.16.0
  - jinja2=2.11.1
  - jpeg=9b
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.2
  - jupyter_core=4.6.3
  - jupyterlab=2.0.1
  - jupyterlab_server=1.1.0
  - lazy-object-proxy=1.4.3
  - libcxx=9.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libsodium=1.0.16
  - libtiff=4.1.0
  - markupsafe=1.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - mypy_extensions=0.4.3
  - nbconvert=5.6.1
  - ncurses=6.2
  - ninja=1.9.0
  - nodeenv=1.3.5
  - notebook=6.0.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.3
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.2
  - pathspec=0.7.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pluggy=0.13.1
  - pre-commit=2.2.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - prompt_toolkit=3.0.4
  - ptyprocess=0.6.0
  - py=1.8.1
  - pycparser=2.20
  - pygments=2.6.1
  - pylint=2.4.4
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - pytest=5.4.1
  - python=3.8.2
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.5.0
  - pyyaml=5.3.1
  - readline=8.0
  - regex=2020.4.4
  - requests=2.23.0
  - send2trash=1.5.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.31.1
  - testpath=0.4.4
  - tk=8.6.8
  - toml=0.10.0
  - torchvision=0.6.0
  - tqdm=4.44.1
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.1
  - urllib3=1.25.8
  - virtualenv=16.7.5
  - wcwidth=0.1.9
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.1.7
  - zeromq=4.3.1
  - zipp=2.2.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.9.0
    - aiohttp==3.6.2
    - altair==4.1.0
    - astor==0.8.1
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - base58==2.0.0
    - beautifulsoup4==4.9.0
    - blinker==1.4
    - boto3==1.12.36
    - botocore==1.15.36
    - cachetools==4.0.0
    - cloudpickle==1.3.0
    - colorama==0.4.3
    - cycler==0.10.0
    - cython==0.29.16
    - dm-tree==0.1.4
    - docutils==0.15.2
    - enum-compat==0.0.3
    - fasteners==0.15
    - filelock==3.0.12
    - future==0.18.2
    - glfw==1.11.0
    - google==2.0.3
    - google-auth==1.14.0
    - google-auth-oauthlib==0.4.1
    - grpcio==1.28.1
    - gym==0.17.1
    - gym-cartpole-swingup==0.0.7
    - imageio==2.8.0
    - ipywidgets==7.5.1
    - jmespath==0.9.5
    - kiwisolver==1.2.0
    - lz4==3.0.2
    - markdown==3.2.1
    - matplotlib==3.2.1
    - monotonic==1.5
    - multidict==4.7.5
    - nbformat==5.0.5
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - opencv-python-headless==4.2.0.34
    - pandas==1.0.3
    - pathtools==0.1.2
    - protobuf==3.11.3
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==2.7.2
    - pydeck==0.3.0b4
    - pyglet==1.5.0
    - pytz==2019.3
    - pyzmq==19.0.0
    - ray==0.8.4
    - redis==3.4.1
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - s3transfer==0.3.3
    - scipy==1.4.1
    - seaborn==0.10.0
    - soupsieve==2.0
    - streamlit==0.58.0
    - tabulate==0.8.7
    - tensorboard==2.2.0
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorboardx==2.0
    - terminado==0.8.3
    - toolz==0.10.0
    - tornado==5.1.1
    - tzlocal==2.0.0
    - validators==0.14.3
    - watchdog==0.10.2
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
    - yarl==1.4.2
