#!/usr/bin/env python
"""Executable that lints commit messages"""
# Adapted from:
# https://github.com/rlworkgroup/viskit/blob/master/scripts/check_commit_message
import sys


def main():
    """Checks for proper line lengths"""
    # Get the commit message location
    commit_msg_filepath = sys.argv[1]

    # Extract the message lines into a list
    lines = list((line.rstrip() for line in open(commit_msg_filepath, "r")))

    # Remove all commented lines
    lines = [line for line in lines if not line or not line.startswith("#")]

    exit_code = 0

    # Error: invalid subject line length
    if len(lines[0]) > 50:
        print("Error: your subject line must be within 50 characters.")
        exit_code = 1

    # No body paragraph
    if len(lines) == 1:
        sys.exit(exit_code)

    lines = lines[2:]

    count = 0
    for line in lines:
        count += 1
        # Ignore newline
        if not line:
            continue

        # Ignore lines originationg from --verbose (diffs)
        if line.startswith("diff --git"):
            break

        # Ignore lines containing URLs, which can get long
        if "http" in line:
            continue

        # Error: invalid body paragraph length
        if len(line) > 72:
            print(
                "Error: line {} of your body paragraph "
                "must be wrapped to 72 characters:".format(count)
            )
            print(">> " + line)
            exit_code = 1

    sys.exit(exit_code)


if __name__ == "__main__":
    main()
