# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Poetry package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Install
      uses: abatilo/actions-poetry@1.0.0
      with:
        python_version: ${{ matrix.python-version }}
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@1.0.0
      with:
        python_version: ${{ matrix.python-version }}
        args: run pytest
